# Generated by Django 3.2.7 on 2021-10-31 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='doj',
            field=models.DateField(default=None, null=True),
        ),
    ]
